import type { Motorcycle } from '../types';

export const motorcycles: Motorcycle[] = [
  {
    licensePlate: 'B 1234 ABC',
    vin: 'MH2JC5940NK123456',
    ccu_number: 'CCU-001',
    stockStatus: 'AVAILABLE',
    model: 'H1',
    color: 'Midnight Blue',
    sku: 'H1-MB',
    productionYear: '2024',
    ownerType: 'FIXED_ASSET',
    ownerName: 'ELECTRUM',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 5678 DEF',
    vin: 'MH2JC5940NK789012',
    ccu_number: 'CCU-002',
    stockStatus: 'RENTED',
    model: 'H1',
    color: 'Tiffany Blue',
    sku: 'H1-TB',
    productionYear: '2024',
    ownerType: 'ROU_ASSET',
    ownerName: 'AIZEN',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 9012 GHI',
    vin: 'MH2JC5940NK345678',
    ccu_number: 'CCU-003',
    stockStatus: 'AVAILABLE',
    model: 'H3',
    color: 'Midnight Blue',
    sku: 'H3-MB',
    productionYear: '2023',
    ownerType: 'ROU_ASSET',
    ownerName: 'DIPO',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 3456 JKL',
    vin: 'MH2JC5940NK901234',
    ccu_number: 'CCU-004',
    stockStatus: 'IN_MAINTENANCE',
    model: 'H3',
    color: 'Tiffany Blue',
    sku: 'H3-TB',
    productionYear: '2023',
    ownerType: 'FIXED_ASSET',
    ownerName: 'ELECTRUM',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 7890 MNO',
    vin: 'MH2JC5940NK567890',
    ccu_number: 'CCU-005',
    stockStatus: 'RENTED_TO_PARTNER',
    model: 'H5',
    color: 'Midnight Blue',
    sku: 'H5-MB',
    productionYear: '2023',
    ownerType: 'ROU_ASSET',
    ownerName: 'TAKARI',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 2468 PQR',
    vin: 'MH2JC5940NK121314',
    ccu_number: 'CCU-006',
    stockStatus: 'HEAVY_DAMAGED',
    model: 'H5',
    color: 'Tiffany Blue',
    sku: 'H5-TB',
    productionYear: '2022',
    ownerType: 'FIXED_ASSET',
    ownerName: 'ELECTRUM',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 1357 STU',
    vin: 'MH2JC5940NK151617',
    ccu_number: 'CCU-007',
    stockStatus: 'WRITE_OFF',
    model: 'H1',
    color: 'Midnight Blue',
    sku: 'H1-MB',
    productionYear: '2024',
    ownerType: 'ROU_ASSET',
    ownerName: 'AIZEN',
    location: 'WH-PI',
  },
  {
    licensePlate: 'B 8642 VWX',
    vin: 'MH2JC5940NK181920',
    ccu_number: 'CCU-008',
    stockStatus: 'AVAILABLE',
    model: 'H3',
    color: 'Tiffany Blue',
    sku: 'H3-TB',
    productionYear: '2024',
    ownerType: 'FIXED_ASSET',
    ownerName: 'ELECTRUM',
    location: 'WH-BKS',
  },
  {
    licensePlate: 'B 9753 YZA',
    vin: 'MH2JC5940NK212223',
    ccu_number: 'CCU-009',
    stockStatus: 'RENTED',
    model: 'H5',
    color: 'Midnight Blue',
    sku: 'H5-MB',
    productionYear: '2024',
    ownerType: 'ROU_ASSET',
    ownerName: 'TAKARI',
    location: 'WH-SBY',
  },
  {
    licensePlate: 'B 4682 BCD',
    vin: 'MH2JC5940NK242526',
    ccu_number: 'CCU-010',
    stockStatus: 'AVAILABLE',
    model: 'H1',
    color: 'Tiffany Blue',
    sku: 'H1-TB',
    productionYear: '2024',
    ownerType: 'FIXED_ASSET',
    ownerName: 'ELECTRUM',
    location: 'WH-BKS',
  },
];

export const statusCounts = {
  All: motorcycles.length,
  AVAILABLE: motorcycles.filter(item => item.stockStatus === 'AVAILABLE').length,
  RENTED: motorcycles.filter(item => item.stockStatus === 'RENTED').length,
  RENTED_TO_PARTNER: motorcycles.filter(item => item.stockStatus === 'RENTED_TO_PARTNER').length,
  IN_MAINTENANCE: motorcycles.filter(item => item.stockStatus === 'IN_MAINTENANCE').length,
  HEAVY_DAMAGED: motorcycles.filter(item => item.stockStatus === 'HEAVY_DAMAGED').length,
  LOST: motorcycles.filter(item => item.stockStatus === 'LOST').length,
  IN_INSPECTION: motorcycles.filter(item => item.stockStatus === 'IN_INSPECTION').length,
  WRITE_OFF: motorcycles.filter(item => item.stockStatus === 'WRITE_OFF').length,
};